# Encoding

## Machine Learning Journey

**Topic:** Encoding

**Author:** Pooja Goswami

### Techniques Covered

- Label Encoding
- One-Hot Encoding
- Ordinal Encoding

In [1]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OrdinalEncoder

In [2]:
df = pd.read_csv("../datasets/02_encoding.csv")

print("Original Dataset")
df

Original Dataset

   id    city  gender education
0   1   Delhi    Male    School
1   2  Mumbai  Female   College
2   3   Delhi  Female    School
3   4    Pune    Male       PhD
4   5  Mumbai    Male   College
5   6   Delhi  Female       PhD

In [3]:
# Label Encoding

label_encoder = LabelEncoder()

df_label = df.copy()

df_label["gender"] = label_encoder.fit_transform(df_label["gender"])

print("Label Encoded Data")

df_label

Label Encoded Data

   id    city  gender education
0   1   Delhi       1    School
1   2  Mumbai       0   College
2   3   Delhi       0    School
3   4    Pune       1       PhD
4   5  Mumbai       1   College
5   6   Delhi       0       PhD

In [4]:
# One Hot Encoding

df_onehot = df.copy()

one_hot = pd.get_dummies(
    df_onehot,
    columns=["city"],
    dtype=int
)

print("One Hot Encoded Data")

one_hot

One Hot Encoded Data

   id  gender education  city_Delhi  city_Mumbai  city_Pune
0   1    Male    School           1            0          0
1   2  Female   College           0            1          0
2   3  Female    School           1            0          0
3   4    Male       PhD           0            0          1
4   5    Male   College           0            1          0
5   6  Female       PhD           1            0          0

In [5]:
# Ordinal Encoding

df_ordinal = df.copy()

ordinal_encoder = OrdinalEncoder(
    categories=[["School", "College", "PhD"]]
)

df_ordinal[["education"]] = ordinal_encoder.fit_transform(
    df_ordinal[["education"]]
)

print("Ordinal Encoded Data")

df_ordinal

Ordinal Encoded Data

   id    city  gender  education
0   1   Delhi    Male        0.0
1   2  Mumbai  Female        1.0
2   3   Delhi  Female        0.0
3   4    Pune    Male        2.0
4   5  Mumbai    Male        1.0
5   6   Delhi  Female        2.0

# Conclusion

This notebook demonstrates three commonly used encoding techniques.

- Label Encoding
- One-Hot Encoding
- Ordinal Encoding

Encoding converts categorical data into numerical form before training Machine Learning models.